import Head from 'next/head'
import Link from 'next/link'
import { Inter } from '@next/font/google'
import styles from '../styles/Home.module.css'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Project 16:16</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="nav-container">
      <nav aria-labelledby='nav-label'>
          <h2 id="nav-label" className={styles.vh}>Site</h2>
        <div>
          <Link href="/"><span className={styles.vh}>16:16 home page</span></Link>
        </div>
        <ul>
          <li><a>About</a></li>
          <li><a>Log</a></li>
          <li><a>Upcoming</a></li>
          <li><a>Subscribe</a></li>
          {/** @todo add space for a serviceworker installed status indicator, and notification counter */}
        </ul>
        </nav>
        </div>
      <main className={styles.main}>
        
      </main>
    </>
  )
}
